//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TurismoRealWebw.DALC
{
    using System;
    using System.Collections.Generic;
    
    public partial class DEPARTAMENTO
    {
        public DEPARTAMENTO()
        {
            this.IMPUESTOes = new HashSet<IMPUESTO>();
            this.OBJETO_HABITACION = new HashSet<OBJETO_HABITACION>();
            this.MANTENCIONs = new HashSet<MANTENCION>();
            this.RESERVAs = new HashSet<RESERVA>();
        }
    
        public decimal ID_DEPARTAMENTO { get; set; }
        public string DIRECCION { get; set; }
        public Nullable<decimal> COSTO_DEPARTAMENTO { get; set; }
        public string ESTADO_DEPARTAMENTO { get; set; }
        public string DESCRIPCION_ESTADO_DEPARTAMENTO { get; set; }
        public string ORIENTACION_DEPARTAMENTO { get; set; }
        public string ESTACIONAMIENTO { get; set; }
        public Nullable<decimal> NUM_HABITACIONES { get; set; }
        public Nullable<decimal> NUM_BAÑO { get; set; }
        public Nullable<decimal> NUM_ESTACIONAMIENTO { get; set; }
        public decimal COMUNA_ID_COMUNA { get; set; }
        public decimal COMUNA_PROVINCIA_ID_PROVINCIA { get; set; }
        public decimal COMUNA_PROVINCIA_REGION_ID_REGION { get; set; }
    
        public virtual COMUNA COMUNA { get; set; }
        public virtual ICollection<IMPUESTO> IMPUESTOes { get; set; }
        public virtual ICollection<OBJETO_HABITACION> OBJETO_HABITACION { get; set; }
        public virtual ICollection<MANTENCION> MANTENCIONs { get; set; }
        public virtual ICollection<RESERVA> RESERVAs { get; set; }
    }
}
