//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TurismoRealWebw.DALC
{
    using System;
    using System.Collections.Generic;
    
    public partial class PROVINCIA
    {
        public PROVINCIA()
        {
            this.COMUNAs = new HashSet<COMUNA>();
        }
    
        public decimal ID_PROVINCIA { get; set; }
        public string NOMBRE_PROVINCIA { get; set; }
        public decimal REGION_ID_REGION { get; set; }
    
        public virtual ICollection<COMUNA> COMUNAs { get; set; }
        public virtual REGION REGION { get; set; }
    }
}
