//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TurismoRealWebw.DALC
{
    using System;
    using System.Collections.Generic;
    
    public partial class RESERVA
    {
        public RESERVA()
        {
            this.PAGOes = new HashSet<PAGO>();
            this.DEPARTAMENTOes = new HashSet<DEPARTAMENTO>();
            this.SERVICIOs = new HashSet<SERVICIO>();
            this.TOURs = new HashSet<TOUR>();
        }
    
        public decimal ID_RESERVA { get; set; }
        public Nullable<System.DateTime> FECHA_ENTRADA { get; set; }
        public Nullable<System.DateTime> FECHA_SALIDA { get; set; }
        public string FIRMA_CONFORMIDAD_CLIENTE { get; set; }
        public string USUARIO_ID_USUARIO { get; set; }
        public decimal CHECK_OUT_ID_CHECK_OUT { get; set; }
    
        public virtual CHECK_OUT CHECK_OUT { get; set; }
        public virtual ICollection<PAGO> PAGOes { get; set; }
        public virtual USUARIO USUARIO { get; set; }
        public virtual ICollection<DEPARTAMENTO> DEPARTAMENTOes { get; set; }
        public virtual ICollection<SERVICIO> SERVICIOs { get; set; }
        public virtual ICollection<TOUR> TOURs { get; set; }
    }
}
