//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TurismoRealWebw.DALC
{
    using System;
    using System.Collections.Generic;
    
    public partial class SERVICIO
    {
        public SERVICIO()
        {
            this.RESERVAs = new HashSet<RESERVA>();
        }
    
        public decimal ID_SERVICIO { get; set; }
        public string NOMBRE_SERVICIO { get; set; }
        public Nullable<System.DateTime> FECHA_SERVICIO { get; set; }
        public decimal CONTRATO_ID_CONTRATO { get; set; }
        public string CONTRATO_PROVEEDOR_ID_PROVEEDOR { get; set; }
    
        public virtual CONTRATO CONTRATO { get; set; }
        public virtual ICollection<RESERVA> RESERVAs { get; set; }
    }
}
