//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TurismoRealWebw.DALC
{
    using System;
    using System.Collections.Generic;
    
    public partial class TRANSPORTE
    {
        public decimal ID_TRANSPORTE { get; set; }
        public string LUGAR_RECOGIDA { get; set; }
        public Nullable<System.DateTime> FECHA_RECOGIDA { get; set; }
    }
}
