//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TurismoRealWebw.DALC
{
    using System;
    using System.Collections.Generic;
    
    public partial class USUARIO
    {
        public USUARIO()
        {
            this.RESERVAs = new HashSet<RESERVA>();
            this.ACOMPAÑANTE = new HashSet<ACOMPAÑANTE>();
        }
    
        public string ID_USUARIO { get; set; }
        public string NOMBRE { get; set; }
        public string APELLIDO { get; set; }
        public string EMAIL { get; set; }
        public string DIRECCION { get; set; }
        public string TELEFONO { get; set; }
        public string CUENTA_USUARIO_ID_CUENTA_USUARIO { get; set; }
    
        public virtual CUENTA_USUARIO CUENTA_USUARIO { get; set; }
        public virtual ICollection<RESERVA> RESERVAs { get; set; }
        public virtual ICollection<ACOMPAÑANTE> ACOMPAÑANTE { get; set; }
    }
}
